import mongoose from "mongoose";

const personalInfoSchema = new mongoose.Schema({
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true,
        unique: true,
    },
    basicInfo: {
        fullName: { type: String, trim: true },
        displayName: { type: String, trim: true },
        profilePhoto: { type: String },
        dob: { type: Date },
        gender: { type: String },
        location: { type: String },
        country: { type: String },
        language: { type: String },
        shortBio: { type: String },
    },
    contactInfo: {
        primaryEmail: { type: String, lowercase: true, trim: true },
        businessEmail: { type: String, lowercase: true, trim: true },
        phone: { type: String },
        whatsapp: { type: String },
        websiteUrl: { type: String },
        address: { type: String },
    },
    professionalDetails: {
        title: { type: String },
        profession: { type: String },
        yearsOfExperience: { type: Number },
        currentPosition: { type: String },
        companyName: { type: String },
        availability: {
            type: String,
            enum: [
                "Available for work",
                "Open to freelance",
                "Open to full-time",
                "Not available",
                "",
            ],
        },
        careerObjective: { type: String },
        professionalSummary: { type: String },
        whatIDo: { type: String },
        whoIHelp: { type: String },
        uniqueSellingPoint: { type: String },
    },
    skills: [{
        name: { type: String },
        category: { type: String },
        level: {
            type: String,
            enum: ["Beginner", "Intermediate", "Advanced", "Expert", ""],
        },
    }, ],
    services: [{
        title: { type: String },
        description: { type: String },
        startingPrice: { type: String },
        deliveryTime: { type: String },
        featured: { type: Boolean, default: false },
    }, ],
    projects: [{
        title: { type: String },
        description: { type: String },
        technologies: { type: [String] },
        category: { type: String },
        liveLink: { type: String },
        githubLink: { type: String },
        imageUrl: { type: String },
        featured: { type: Boolean, default: false },
    }, ],
    experience: [{
        jobTitle: { type: String },
        companyName: { type: String },
        startDate: { type: String },
        endDate: { type: String },
        currentlyWorking: { type: Boolean, default: false },
        location: { type: String },
        description: { type: String },
        keyAchievements: { type: String },
    }, ],
    education: [{
        degree: { type: String },
        institute: { type: String },
        startYear: { type: String },
        endYear: { type: String },
        status: {
            type: String,
            enum: ["Completed", "In Progress", ""],
        },
        description: { type: String },
    }, ],
    socialLinks: {
        linkedin: { type: String },
        github: { type: String },
        facebook: { type: String },
        twitter: { type: String },
        instagram: { type: String },
        youtube: { type: String },
        fiverr: { type: String },
        upwork: { type: String },
        behance: { type: String },
        dribbble: { type: String },
        portfolioUrl: { type: String },
        whatsappLink: { type: String },
    },
    certifications: [{
        title: { type: String },
        issuer: { type: String },
        year: { type: String },
        credentialUrl: { type: String },
        description: { type: String },
    }, ],
    testimonials: [{
        clientName: { type: String },
        clientRole: { type: String },
        reviewText: { type: String },
        rating: { type: Number, min: 1, max: 5 },
        clientImage: { type: String },
    }, ],
    websitePreferences: {
        preferredStyle: { type: String },
        defaultTemplate: { type: String },
        defaultTheme: { type: String },
        preferredTone: {
            type: String,
            enum: [
                "Professional",
                "Friendly",
                "Creative",
                "Minimal",
                "Corporate",
                "",
            ],
        },
        portfolioGoal: { type: String },
        showPhone: { type: Boolean, default: true },
        showEmail: { type: Boolean, default: true },
        showSocialLinks: { type: Boolean, default: true },
        showProjects: { type: Boolean, default: true },
        showTestimonials: { type: Boolean, default: true },
    },
    completionScore: {
        type: Number,
        default: 0,
    },
}, {
    timestamps: true,
}, );

export default mongoose.models.PersonalInfo ||
    mongoose.model("PersonalInfo", personalInfoSchema);