export const WEBSITE_THEMES = {
    emerald: {
        id: "emerald",
        name: "Emerald Fresh",
        description: "Best for portfolios, SaaS, business websites.",
        categoryFit: "business",
        modes: {
            light: {
                primary: "#16A34A",
                secondary: "#047857",
                accent: "#F97316",
                background: "#FFFFFF",
                softBackground: "#F8FAFC",
                text: "#0F172A",
                mutedText: "#64748B",
                border: "#E2E8F0",
            },
            dark: {
                primary: "#22C55E",
                secondary: "#10B981",
                accent: "#FB923C",
                background: "#020617",
                softBackground: "#0F172A",
                text: "#F8FAFC",
                mutedText: "#94A3B8",
                border: "#1E293B",
            },
        },
    },
    modernDark: {
        id: "modernDark",
        name: "Modern Dark",
        description: "Best for AI tools, developers, tech portfolios.",
        categoryFit: "tech",
        modes: {
            light: {
                primary: "#2563EB",
                secondary: "#6366F1",
                accent: "#06B6D4",
                background: "#FFFFFF",
                softBackground: "#F8FAFC",
                text: "#0F172A",
                mutedText: "#64748B",
                border: "#E2E8F0",
            },
            dark: {
                primary: "#22D3EE",
                secondary: "#6366F1",
                accent: "#A855F7",
                background: "#020617",
                softBackground: "#0F172A",
                text: "#F8FAFC",
                mutedText: "#94A3B8",
                border: "#1E293B",
            },
        },
    },
    royalBlue: {
        id: "royalBlue",
        name: "Royal Blue",
        description: "Best for corporate, agencies, professional services.",
        categoryFit: "corporate",
        modes: {
            light: {
                primary: "#2563EB",
                secondary: "#1D4ED8",
                accent: "#38BDF8",
                background: "#FFFFFF",
                softBackground: "#EFF6FF",
                text: "#0F172A",
                mutedText: "#64748B",
                border: "#BFDBFE",
            },
            dark: {
                primary: "#60A5FA",
                secondary: "#3B82F6",
                accent: "#38BDF8",
                background: "#020617",
                softBackground: "#0F172A",
                text: "#F8FAFC",
                mutedText: "#94A3B8",
                border: "#1E3A8A",
            },
        },
    },
    premiumPurple: {
        id: "premiumPurple",
        name: "Premium Purple",
        description: "Best for creative portfolios, SaaS, agencies.",
        categoryFit: "creative",
        modes: {
            light: {
                primary: "#7C3AED",
                secondary: "#5B21B6",
                accent: "#EC4899",
                background: "#FFFFFF",
                softBackground: "#F5F3FF",
                text: "#111827",
                mutedText: "#6B7280",
                border: "#DDD6FE",
            },
            dark: {
                primary: "#A78BFA",
                secondary: "#8B5CF6",
                accent: "#F472B6",
                background: "#0F0A1F",
                softBackground: "#1E1B4B",
                text: "#F9FAFB",
                mutedText: "#C4B5FD",
                border: "#4C1D95",
            },
        },
    },
    minimalBlack: {
        id: "minimalBlack",
        name: "Minimal Black",
        description: "Best for minimal portfolios, personal brands, studios.",
        categoryFit: "portfolio",
        modes: {
            light: {
                primary: "#111827",
                secondary: "#374151",
                accent: "#9CA3AF",
                background: "#FFFFFF",
                softBackground: "#F9FAFB",
                text: "#111827",
                mutedText: "#6B7280",
                border: "#E5E7EB",
            },
            dark: {
                primary: "#F9FAFB",
                secondary: "#D1D5DB",
                accent: "#9CA3AF",
                background: "#030712",
                softBackground: "#111827",
                text: "#F9FAFB",
                mutedText: "#9CA3AF",
                border: "#374151",
            },
        },
    },
    warmBusiness: {
        id: "warmBusiness",
        name: "Warm Business",
        description: "Best for business websites, consultants, local brands.",
        categoryFit: "business",
        modes: {
            light: {
                primary: "#EA580C",
                secondary: "#9A3412",
                accent: "#F59E0B",
                background: "#FFFBEB",
                softBackground: "#FFF7ED",
                text: "#1C1917",
                mutedText: "#78716C",
                border: "#FED7AA",
            },
            dark: {
                primary: "#FB923C",
                secondary: "#FDBA74",
                accent: "#FACC15",
                background: "#1C1917",
                softBackground: "#292524",
                text: "#FFFBEB",
                mutedText: "#FDBA74",
                border: "#7C2D12",
            },
        },
    },
    creativeGradient: {
        id: "creativeGradient",
        name: "Creative Gradient",
        description: "Best for designers, agencies, creative websites.",
        categoryFit: "creative",
        modes: {
            light: {
                primary: "#8B5CF6",
                secondary: "#EC4899",
                accent: "#06B6D4",
                background: "#FFFFFF",
                softBackground: "#FDF4FF",
                text: "#111827",
                mutedText: "#6B7280",
                border: "#E9D5FF",
            },
            dark: {
                primary: "#A78BFA",
                secondary: "#F472B6",
                accent: "#22D3EE",
                background: "#111827",
                softBackground: "#1F2937",
                text: "#F9FAFB",
                mutedText: "#D1D5DB",
                border: "#4B5563",
            },
        },
    },
    luxuryGold: {
        id: "luxuryGold",
        name: "Luxury Gold",
        description: "Best for luxury brands, premium services, real estate.",
        categoryFit: "luxury",
        modes: {
            light: {
                primary: "#B45309",
                secondary: "#92400E",
                accent: "#FACC15",
                background: "#FFFFFF",
                softBackground: "#FFFBEB",
                text: "#1C1917",
                mutedText: "#78716C",
                border: "#FDE68A",
            },
            dark: {
                primary: "#D97706",
                secondary: "#F59E0B",
                accent: "#FACC15",
                background: "#0A0A0A",
                softBackground: "#171717",
                text: "#FAFAFA",
                mutedText: "#A3A3A3",
                border: "#404040",
            },
        },
    },
    medicalClean: {
        id: "medicalClean",
        name: "Medical Clean",
        description: "Best for clinics, doctors, health websites.",
        categoryFit: "health",
        modes: {
            light: {
                primary: "#0EA5E9",
                secondary: "#0F766E",
                accent: "#22C55E",
                background: "#FFFFFF",
                softBackground: "#F0FDFA",
                text: "#0F172A",
                mutedText: "#64748B",
                border: "#BAE6FD",
            },
            dark: {
                primary: "#38BDF8",
                secondary: "#2DD4BF",
                accent: "#4ADE80",
                background: "#020617",
                softBackground: "#0F172A",
                text: "#F8FAFC",
                mutedText: "#94A3B8",
                border: "#164E63",
            },
        },
    },
    restaurantWarm: {
        id: "restaurantWarm",
        name: "Restaurant Warm",
        description: "Best for restaurants, cafes, food brands.",
        categoryFit: "food",
        modes: {
            light: {
                primary: "#DC2626",
                secondary: "#EA580C",
                accent: "#FACC15",
                background: "#FFFBEB",
                softBackground: "#FFF7ED",
                text: "#1C1917",
                mutedText: "#78716C",
                border: "#FED7AA",
            },
            dark: {
                primary: "#F87171",
                secondary: "#FB923C",
                accent: "#FACC15",
                background: "#1C1917",
                softBackground: "#292524",
                text: "#FFFBEB",
                mutedText: "#FDBA74",
                border: "#7F1D1D",
            },
        },
    },
    techNeon: {
        id: "techNeon",
        name: "Tech Neon",
        description: "Best for SaaS, AI tools, tech startups.",
        categoryFit: "tech",
        modes: {
            light: {
                primary: "#06B6D4",
                secondary: "#2563EB",
                accent: "#A855F7",
                background: "#FFFFFF",
                softBackground: "#ECFEFF",
                text: "#0F172A",
                mutedText: "#64748B",
                border: "#BAE6FD",
            },
            dark: {
                primary: "#22D3EE",
                secondary: "#60A5FA",
                accent: "#C084FC",
                background: "#020617",
                softBackground: "#0F172A",
                text: "#F8FAFC",
                mutedText: "#94A3B8",
                border: "#1E293B",
            },
        },
    },
    corporateSlate: {
        id: "corporateSlate",
        name: "Corporate Slate",
        description: "Best for corporate, consulting, finance.",
        categoryFit: "corporate",
        modes: {
            light: {
                primary: "#334155",
                secondary: "#475569",
                accent: "#0EA5E9",
                background: "#FFFFFF",
                softBackground: "#F8FAFC",
                text: "#0F172A",
                mutedText: "#64748B",
                border: "#E2E8F0",
            },
            dark: {
                primary: "#94A3B8",
                secondary: "#CBD5E1",
                accent: "#38BDF8",
                background: "#020617",
                softBackground: "#111827",
                text: "#F8FAFC",
                mutedText: "#94A3B8",
                border: "#334155",
            },
        },
    },
    educationCalm: {
        id: "educationCalm",
        name: "Education Calm",
        description: "Best for schools, courses, teachers, academies.",
        categoryFit: "education",
        modes: {
            light: {
                primary: "#4F46E5",
                secondary: "#2563EB",
                accent: "#F59E0B",
                background: "#FFFFFF",
                softBackground: "#EEF2FF",
                text: "#111827",
                mutedText: "#6B7280",
                border: "#C7D2FE",
            },
            dark: {
                primary: "#818CF8",
                secondary: "#60A5FA",
                accent: "#FBBF24",
                background: "#020617",
                softBackground: "#111827",
                text: "#F9FAFB",
                mutedText: "#9CA3AF",
                border: "#3730A3",
            },
        },
    },
    realEstateElite: {
        id: "realEstateElite",
        name: "Real Estate Elite",
        description: "Best for property, real estate, architecture.",
        categoryFit: "real estate",
        modes: {
            light: {
                primary: "#0F766E",
                secondary: "#115E59",
                accent: "#C2410C",
                background: "#FFFFFF",
                softBackground: "#F0FDFA",
                text: "#134E4A",
                mutedText: "#64748B",
                border: "#CCFBF1",
            },
            dark: {
                primary: "#2DD4BF",
                secondary: "#5EEAD4",
                accent: "#FB923C",
                background: "#042F2E",
                softBackground: "#0F172A",
                text: "#F0FDFA",
                mutedText: "#99F6E4",
                border: "#115E59",
            },
        },
    },
    fashionRose: {
        id: "fashionRose",
        name: "Fashion Rose",
        description: "Best for fashion, beauty, personal brands.",
        categoryFit: "fashion",
        modes: {
            light: {
                primary: "#E11D48",
                secondary: "#BE123C",
                accent: "#F472B6",
                background: "#FFFFFF",
                softBackground: "#FFF1F2",
                text: "#1F2937",
                mutedText: "#6B7280",
                border: "#FFE4E6",
            },
            dark: {
                primary: "#FB7185",
                secondary: "#F472B6",
                accent: "#FDA4AF",
                background: "#1F0A12",
                softBackground: "#2A1018",
                text: "#FFF1F2",
                mutedText: "#FDA4AF",
                border: "#881337",
            },
        },
    },
    natureOrganic: {
        id: "natureOrganic",
        name: "Nature Organic",
        description: "Best for agriculture, eco brands, wellness.",
        categoryFit: "wellness",
        modes: {
            light: {
                primary: "#65A30D",
                secondary: "#166534",
                accent: "#D97706",
                background: "#FFFFFF",
                softBackground: "#F7FEE7",
                text: "#1A2E05",
                mutedText: "#64748B",
                border: "#D9F99D",
            },
            dark: {
                primary: "#A3E635",
                secondary: "#4ADE80",
                accent: "#FBBF24",
                background: "#0F1F0A",
                softBackground: "#14230D",
                text: "#F7FEE7",
                mutedText: "#BEF264",
                border: "#365314",
            },
        },
    },
    startupCoral: {
        id: "startupCoral",
        name: "Startup Coral",
        description: "Best for startups, landing pages, product launches.",
        categoryFit: "startup",
        modes: {
            light: {
                primary: "#F97316",
                secondary: "#EF4444",
                accent: "#14B8A6",
                background: "#FFFFFF",
                softBackground: "#FFF7ED",
                text: "#111827",
                mutedText: "#6B7280",
                border: "#FED7AA",
            },
            dark: {
                primary: "#FB923C",
                secondary: "#F87171",
                accent: "#2DD4BF",
                background: "#1C1917",
                softBackground: "#292524",
                text: "#FFFBEB",
                mutedText: "#FDBA74",
                border: "#7C2D12",
            },
        },
    },
    financeEmerald: {
        id: "financeEmerald",
        name: "Finance Emerald",
        description: "Best for finance, fintech, accounting.",
        categoryFit: "finance",
        modes: {
            light: {
                primary: "#059669",
                secondary: "#047857",
                accent: "#2563EB",
                background: "#FFFFFF",
                softBackground: "#ECFDF5",
                text: "#064E3B",
                mutedText: "#64748B",
                border: "#A7F3D0",
            },
            dark: {
                primary: "#34D399",
                secondary: "#10B981",
                accent: "#60A5FA",
                background: "#022C22",
                softBackground: "#064E3B",
                text: "#ECFDF5",
                mutedText: "#A7F3D0",
                border: "#047857",
            },
        },
    },
    creativeStudio: {
        id: "creativeStudio",
        name: "Creative Studio",
        description: "Best for agencies, designers, freelancers.",
        categoryFit: "creative",
        modes: {
            light: {
                primary: "#DB2777",
                secondary: "#7C3AED",
                accent: "#06B6D4",
                background: "#FFFFFF",
                softBackground: "#FDF2F8",
                text: "#111827",
                mutedText: "#6B7280",
                border: "#FBCFE8",
            },
            dark: {
                primary: "#F472B6",
                secondary: "#A78BFA",
                accent: "#22D3EE",
                background: "#111827",
                softBackground: "#1F2937",
                text: "#F9FAFB",
                mutedText: "#D1D5DB",
                border: "#4B5563",
            },
        },
    },
    cleanMint: {
        id: "cleanMint",
        name: "Clean Mint",
        description: "Best for modern portfolios, clean business websites.",
        categoryFit: "portfolio",
        modes: {
            light: {
                primary: "#10B981",
                secondary: "#14B8A6",
                accent: "#6366F1",
                background: "#FFFFFF",
                softBackground: "#F0FDFA",
                text: "#0F172A",
                mutedText: "#64748B",
                border: "#CCFBF1",
            },
            dark: {
                primary: "#5EEAD4",
                secondary: "#34D399",
                accent: "#818CF8",
                background: "#020617",
                softBackground: "#0F172A",
                text: "#F8FAFC",
                mutedText: "#94A3B8",
                border: "#1E293B",
            },
        },
    },
    pureMonochrome: {
        id: "pureMonochrome",
        name: "Pure Black & White",
        description: "Best for bold minimal portfolios, editorial, high-contrast brands.",
        categoryFit: "portfolio",
        modes: {
            light: {
                primary: "#000000",
                secondary: "#111111",
                accent: "#333333",
                background: "#FFFFFF",
                softBackground: "#F5F5F5",
                text: "#000000",
                mutedText: "#555555",
                border: "#D1D1D1",
            },
            dark: {
                primary: "#FFFFFF",
                secondary: "#E5E5E5",
                accent: "#CCCCCC",
                background: "#000000",
                softBackground: "#111111",
                text: "#FFFFFF",
                mutedText: "#AAAAAA",
                border: "#333333",
            },
        },
    },
};

export const DEFAULT_THEME_KEY = "emerald";
export const DEFAULT_THEME_MODE = "light";

export function getTheme(themeKey, mode = "light") {
    const theme = WEBSITE_THEMES[themeKey] || WEBSITE_THEMES[DEFAULT_THEME_KEY];
    const safeMode = mode === "dark" ? "dark" : "light"; // System resolution logic usually implemented on client
    return {
        ...theme,
        colors: theme.modes[safeMode],
    };
}
