import "server-only";

const get = (key, fallback = "") => process.env[key] || fallback;

export const serverEnv = {
  NODE_ENV: get("NODE_ENV", "development"),
  MONGODB_URI: get("MONGODB_URI"),
  JWT_SECRET: get("JWT_SECRET"),
  ROOT_SUPER_ADMIN_EMAIL: get("ROOT_SUPER_ADMIN_EMAIL"),
  GOOGLE_CLIENT_ID: get("GOOGLE_CLIENT_ID"),
  GOOGLE_CLIENT_SECRET: get("GOOGLE_CLIENT_SECRET"),
  GOOGLE_REDIRECT_URI: get("GOOGLE_REDIRECT_URI"),
  GEMINI_API_KEY: get("GEMINI_API_KEY"),
  GOOGLE_GENERATIVE_AI_API_KEY: get("GOOGLE_GENERATIVE_AI_API_KEY"),
  GOOGLE_API_KEY: get("GOOGLE_API_KEY"),
  GEMINI_MODEL: get("GEMINI_MODEL"),
  GEMINI_MODELS: get("GEMINI_MODELS"),
  CLOUDINARY_URL: get("CLOUDINARY_URL"),
  CLOUDINARY_CLOUD_NAME: get("CLOUDINARY_CLOUD_NAME"),
  CLOUDINARY_API_KEY: get("CLOUDINARY_API_KEY"),
  CLOUDINARY_API_SECRET: get("CLOUDINARY_API_SECRET"),
  SMTP_HOST: get("SMTP_HOST"),
  SMTP_PORT: get("SMTP_PORT", "587"),
  SMTP_USER: get("SMTP_USER"),
  SMTP_PASS: get("SMTP_PASS"),
  EMAIL_FROM: get("EMAIL_FROM"),
  CONTACT_NOTIFY_EMAIL: get("CONTACT_NOTIFY_EMAIL"),
  CRON_SECRET: get("CRON_SECRET"),
  NEXT_PUBLIC_APP_URL: get("NEXT_PUBLIC_APP_URL"),
  APP_URL: get("APP_URL"),
  VERCEL_URL: get("VERCEL_URL"),
  MEMBERSHIP_INVITE_SECRET: get("MEMBERSHIP_INVITE_SECRET"),
  SMTP_FROM: get("SMTP_FROM"),
  UPSTASH_REDIS_REST_URL: get("UPSTASH_REDIS_REST_URL"),
  UPSTASH_REDIS_REST_TOKEN: get("UPSTASH_REDIS_REST_TOKEN"),
  REDIS_URL: get("REDIS_URL"),
  CACHE_ENABLED: get("CACHE_ENABLED", "true"),
  CACHE_DEFAULT_TTL_SECONDS: Number(get("CACHE_DEFAULT_TTL_SECONDS", "300")),
  CACHE_PUBLIC_TTL_SECONDS: Number(get("CACHE_PUBLIC_TTL_SECONDS", "600")),
  CACHE_PRIVATE_TTL_SECONDS: Number(get("CACHE_PRIVATE_TTL_SECONDS", "120")),
  CACHE_LONG_TTL_SECONDS: Number(get("CACHE_LONG_TTL_SECONDS", "3600")),
  PAYMENTS_ENABLED: get("PAYMENTS_ENABLED", "false"),
  PAYMENT_DEFAULT_CURRENCY: get("PAYMENT_DEFAULT_CURRENCY", "PKR"),
  PAYMENT_SUCCESS_URL: get("PAYMENT_SUCCESS_URL"),
  PAYMENT_CANCEL_URL: get("PAYMENT_CANCEL_URL"),
  PAYMENT_WEBHOOK_SECRET: get("PAYMENT_WEBHOOK_SECRET"),
  PAYMENT_IDEMPOTENCY_SECRET: get("PAYMENT_IDEMPOTENCY_SECRET"),
  CARD_GATEWAY_PROVIDER: get("CARD_GATEWAY_PROVIDER"),
  CARD_GATEWAY_PUBLIC_KEY: get("CARD_GATEWAY_PUBLIC_KEY"),
  CARD_GATEWAY_SECRET_KEY: get("CARD_GATEWAY_SECRET_KEY"),
  CARD_GATEWAY_WEBHOOK_SECRET: get("CARD_GATEWAY_WEBHOOK_SECRET"),
  JAZZCASH_ENABLED: get("JAZZCASH_ENABLED", "false"),
  JAZZCASH_MERCHANT_ID: get("JAZZCASH_MERCHANT_ID"),
  JAZZCASH_PASSWORD: get("JAZZCASH_PASSWORD"),
  JAZZCASH_INTEGRITY_SALT: get("JAZZCASH_INTEGRITY_SALT"),
  JAZZCASH_RETURN_URL: get("JAZZCASH_RETURN_URL"),
  EASYPAISA_ENABLED: get("EASYPAISA_ENABLED", "false"),
  EASYPAISA_STORE_ID: get("EASYPAISA_STORE_ID"),
  EASYPAISA_HASH_KEY: get("EASYPAISA_HASH_KEY"),
  EASYPAISA_RETURN_URL: get("EASYPAISA_RETURN_URL"),
  MANUAL_PAYMENT_ENABLED: get("MANUAL_PAYMENT_ENABLED", "false"),
};

export function requireServerEnv(key) {
  const value = serverEnv[key];
  if (!value) {
    throw new Error(`${key} is not configured.`);
  }
  return value;
}

export function getPublicBaseUrl() {
  if (serverEnv.APP_URL) {
    return serverEnv.APP_URL.replace(/\/$/, "");
  }
  if (serverEnv.NEXT_PUBLIC_APP_URL) {
    return serverEnv.NEXT_PUBLIC_APP_URL.replace(/\/$/, "");
  }
  if (serverEnv.VERCEL_URL) return `https://${serverEnv.VERCEL_URL}`.replace(/\/$/, "");
  return "http://localhost:3000";
}
